# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
dist: xenial
julia:
  - 1.1
#  - nightly
addons:
  apt:
    packages:
      pkg-config
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install pkg-config; fi
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; ENV["PYTHON"]="";Pkg.add("Conda");Pkg.build("FEniCS");'
    - julia -e 'using Pkg, Conda; ENV["PATH"] = "$(Conda.BINDIR);$(ENV["PATH"])";ENV["PKG_CONFIG_PATH"] = "$(Conda.LIBDIR*"/pkgconfig")"; print(ENV["PKG_CONFIG_PATH"]); Pkg.test("FEniCS", coverage=true)'
after_success:
  # push coverage results to Coveralls, .cov files were copied back by script above
  - echo "**** submitting coverage information"
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
